spinnaker:
  redis:
    enabled: false

sql:
  enabled: true
  connectionPools:
    default:
      # additional connection pool parameters are available here,
      # for more detail and to view defaults, see:
      # https://github.com/spinnaker/kork/blob/master/kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/ConnectionPoolProperties.kt
      default: true
      jdbcUrl: jdbc:mysql://${SPINNAKER_DB_HOST}:3306/front50?user=front50_service&password=${SPINNAKER_DB_PASSWORD}
      user: front50_service
      password: ${SPINNAKER_DB_PASSWORD}
  migration:
    user: front50_migrate
    jdbcUrl: jdbc:mysql://${SPINNAKER_DB_HOST}:3306/front50?user=front50_migrate&password=${SPINNAKER_DB_PASSWORD}