currentDeployment: default
deploymentConfigurations:
  - name: default
    version: 1.22.0
    providers:
      appengine:
        enabled: false
        accounts: []
      aws:
        enabled: true
        accounts:
          - name: non-prod
            requiredGroupMembership: []
            providerVersion: V1
            permissions: {}
            accountId: '933943444071'
            regions:
              - name: us-east-1
            assumeRole: role/spinnakerManaged
            lifecycleHooks: []
        primaryAccount: non-prod
        bakeryDefaults:
          baseImages: []
        defaultKeyPairTemplate: '{{name}}-keypair'
        defaultRegions:
          - name: us-east-1
        defaults:
          iamRole: BaseIAMRole
      ecs:
        enabled: false
        accounts: []
      azure:
        enabled: false
        accounts: []
        bakeryDefaults:
          templateFile: azure-linux.json
          baseImages: []
      dcos:
        enabled: false
        accounts: []
        clusters: []
      dockerRegistry:
        enabled: false
        accounts: []
      google:
        enabled: false
        accounts: []
        bakeryDefaults:
          templateFile: gce.json
          baseImages: []
          zone: us-central1-f
          network: default
          useInternalIp: false
      huaweicloud:
        enabled: false
        accounts: []
        bakeryDefaults:
          baseImages: []
      kubernetes:
        enabled: false
        accounts: []
      oracle:
        enabled: false
        accounts: []
        bakeryDefaults:
          templateFile: oci.json
          baseImages: []
      cloudfoundry:
        enabled: false
        accounts: []
    deploymentEnvironment:
      size: SMALL
      type: LocalDebian
      imageVariant: SLIM
      updateVersions: true
      consul:
        enabled: false
      vault:
        enabled: false
      customSizing: {}
      sidecars: {}
      initContainers: {}
      hostAliases: {}
      affinity: {}
      tolerations: {}
      nodeSelectors: {}
      gitConfig:
        upstreamUser: spinnaker
      livenessProbeConfig:
        enabled: false
      haServices:
        clouddriver:
          enabled: false
          disableClouddriverRoDeck: false
        echo:
          enabled: false
    persistentStorage:
      persistentStoreType: redis
      azs: {}
      gcs:
        rootFolder: front50
      redis: {}
      s3:
        rootFolder: front50
      oracle: {}
    features:
      auth: false
      fiat: false
      chaos: false
      entityTags: false
    metricStores:
      datadog:
        enabled: false
        tags: []
      prometheus:
        enabled: false
        add_source_metalabels: true
      stackdriver:
        enabled: false
      newrelic:
        enabled: false
        tags: []
      period: 30
      enabled: false
    notifications:
      slack:
        enabled: false
        botName:
        token:
      twilio:
        enabled: false
        baseUrl: https://api.twilio.com/
      github-status:
        enabled: false
    timezone: America/Los_Angeles
    ci:
      jenkins:
        enabled: true
        masters:
          - name: jenkins-master
            permissions: {}
            address: http://${SPD_JENKINS_PUBLIC_IP}:8080
            username: ${SPD_JENKINS_USERNAME}
            password: ${SPD_JENKINS_PASSWORD}
            csrf: true
      travis:
        enabled: false
        masters: []
      wercker:
        enabled: false
        masters: []
      concourse:
        enabled: false
        masters: []
      gcb:
        enabled: false
        accounts: []
    repository:
      artifactory:
        enabled: false
        searches: []
    security:
      apiSecurity:
        ssl:
          enabled: false
        overrideBaseUrl: http://${SPINNAKER_PUBLIC_IP}:8084
      uiSecurity:
        ssl:
          enabled: false
        overrideBaseUrl: http://${SPINNAKER_PUBLIC_IP}:9000
      authn:
        oauth2:
          enabled: false
          client: {}
          resource: {}
          userInfoMapping: {}
        saml:
          enabled: false
          userAttributeMapping: {}
        ldap:
          enabled: false
        x509:
          enabled: false
        iap:
          enabled: false
        enabled: false
      authz:
        groupMembership:
          service: EXTERNAL
          google:
            roleProviderType: GOOGLE
          github:
            roleProviderType: GITHUB
          file:
            roleProviderType: FILE
          ldap:
            roleProviderType: LDAP
        enabled: false
    artifacts:
      bitbucket:
        enabled: false
        accounts: []
      gcs:
        enabled: false
        accounts: []
      oracle:
        enabled: false
        accounts: []
      github:
        enabled: false
        accounts: []
      gitlab:
        enabled: false
        accounts: []
      gitrepo:
        enabled: false
        accounts: []
      http:
        enabled: false
        accounts: []
      helm:
        enabled: false
        accounts: []
      s3:
        enabled: false
        accounts: []
      maven:
        enabled: false
        accounts: []
      templates: []
    pubsub:
      enabled: false
      google:
        enabled: false
        pubsubType: GOOGLE
        subscriptions: []
        publishers: []
    canary:
      enabled: false
      serviceIntegrations:
        - name: google
          enabled: false
          accounts: []
          gcsEnabled: false
          stackdriverEnabled: false
        - name: prometheus
          enabled: false
          accounts: []
        - name: datadog
          enabled: false
          accounts: []
        - name: signalfx
          enabled: false
          accounts: []
        - name: aws
          enabled: false
          accounts: []
          s3Enabled: false
        - name: newrelic
          enabled: false
          accounts: []
      reduxLoggerEnabled: true
      defaultJudge: NetflixACAJudge-v1.0
      stagesEnabled: true
      templatesEnabled: true
      showAllConfigsEnabled: true
    plugins:
      plugins: []
      enabled: false
      downloadingEnabled: false
    spinnaker:
      extensibility:
        repositories: {}
    webhook:
      trust:
        enabled: false
    telemetry:
      enabled: false
      endpoint: https://stats.spinnaker.io
      instanceId: 01DZZ19MVFQGEJ6DYRNTQPDYXR
      connectionTimeoutMillis: 3000
      readTimeoutMillis: 5000