spring:
  datasource:
    url: jdbc:postgresql://${AWS_DB_HOST:localhost}/petclinic
    username: petclinic
    password: ${AWS_DB_PASSWORD:q1KqZiu3vLnAug}
    driverClassName: org.postgresql.Driver

  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          time_zone: "UTC"
          lob:
            non_contextual_creation: true
    open-in-view: false
  flyway:
    locations: [ "classpath:db/migration/ddl", "classpath:db/migration/dml" ]

security:
  custom:
    login-url: "/login"
    excluded-api: "/actuator/**, /, /login, /test, /css/**, /fonts/**, /img/**, /js/**, /favicon.ico"
  token:
    expiration-time-seconds: 600
    token-prefix: "Bearer"